name: main

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions: {}

jobs:
  build:
    name: main
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: taiki-e/checkout-action@v1
      - uses: actions/setup-python@v5
      - run: pip install pre-commit-mirror-maker
      - run: git config --global user.name 'Github Actions'
      - run: git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
      - run: pre-commit-mirror . --language=node --package-name=oxlint --description="Linter for the JavaScript Oxidation Compiler" --types-or=javascript --types-or=jsx --types-or=ts --types-or=tsx
      - run: |
          git remote set-url origin https://x-access-token:$GH_TOKEN@github.com/$GITHUB_REPOSITORY
          git push origin HEAD:refs/heads/main --tags
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
